services:
  bot_app:
    build: .
    container_name: 2dworkflow_bot
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Istanbul